### ISSUE TITLE
module 'when_will_it_end' has no attribute 'format_time'

### ISSUE THREAD

**Issue by LandSurveyorK** [zkurtz/when_will_it_end#1]
module 'when_will_it_end' has no attribute 'format_time'

dir(when_will_it_end)

Out[13]: 
['LoopProgressMonitor',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__']

**Comment by LandSurveyorK** [comment]
Thank you for your quick response. 

In git bash:

cd ".... /Anaconda3/Lib/site-packages"
git clone https://github.com/zkurtz/when_will_it_end.git 

cd when_will_it_end
python setup.py install

then in Spider:
import when_will_it_end as wwie

dir(wwie)
Out[50]: 
['LoopProgressMonitor',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__']

**Comment by zkurtz** [comment]
I don't know. I'm not a Spyder user, so I wonder if it has something to do with Spyder. I uninstalled the package and re-installed it, and still am not having any problem. I use python only from the terminal. Maybe seeing whether it works at your terminal is the next thing to check?

**Comment by LandSurveyorK** [comment]
Thank you,  it works in the terminal. 
I will go and figure out what's wrong in Spider, thank you again!
